apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: us.icr.io/sn-labs-andymichael/accounts:1
          resources: {}
          env:
            - name: DATABASE_HOST
              value: postgresql
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: accounts-route
spec:
  to:
    kind: Service
    name: accounts-service
  port:
    targetPort: 8080
  tls:
    termination: edge
